---
- name: Bootstrap Python
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Update package cache
      raw: sudo apt-get update

    - name: Install Python 3.9
      raw: sudo apt-get install -y python3.9 python3.9-distutils

- name: Configure application server
  hosts: app
  become: true

  tasks:

    - name: Gather facts
      setup:

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

- name: Configure database server
  hosts: db
  become: true

  tasks:

    - name: Gather facts
      setup:

    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present