---
- name: Configure application server
  hosts: app
  become: true

  tasks:

    - name: Update packages
      apt:
        update_cache: true

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version

    - debug:
        var: java_version.stderr


- name: Configure database server
  hosts: db
  become: true

  tasks:

    - name: Update packages
      apt:
        update_cache: true

    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: true